name: Deploy Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: {{secrets.SUPABASE_ACCESS_TOKEN}}
      PROJECT_ID: {{secrets.SUPABASE_PROJECT_ID}}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: |
        echo "SUPABASE_ACCESS_TOKEN: $SUPABASE_ACCESS_TOKEN"
        echo "PROJECT_ID: $PROJECT_ID"
        echo "Working directory: $(pwd)"


      - run: supabase functions deploy --project-ref $PROJECT_ID --workdir "./supabase"
